'''

Linear regression is a supervised learning algorithm where our target variable is Numerical/continuos.
In linear regression we are trying draw a best fit line for which we are getting the minimum sum of squared error.

Best fit  line: the line for which the error between the predicted value and the actual value is minimum.

'''

In [1]:
import pandas as pd
import numpy as np

In [2]:
bike_data = pd.read_csv(r'C:\Mine\Machine Learning\daily-bike-share.csv')

In [3]:
bike_data.head()

instant    dteday  season  yr  mnth  holiday  weekday  workingday  \
0        1  1/1/2011       1   0     1        0        6           0   
1        2  1/2/2011       1   0     1        0        0           0   
2        3  1/3/2011       1   0     1        0        1           1   
3        4  1/4/2011       1   0     1        0        2           1   
4        5  1/5/2011       1   0     1        0        3           1   

   weathersit      temp     atemp       hum  windspeed  rentals  
0           2  0.344167  0.363625  0.805833   0.160446      331  
1           2  0.363478  0.353739  0.696087   0.248539      131  
2           1  0.196364  0.189405  0.437273   0.248309      120  
3           1  0.200000  0.212122  0.590435   0.160296      108  
4           1  0.226957  0.229270  0.436957   0.186900       82

In [4]:
bike_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 731 entries, 0 to 730
Data columns (total 14 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   instant     731 non-null    int64  
 1   dteday      731 non-null    object 
 2   season      731 non-null    int64  
 3   yr          731 non-null    int64  
 4   mnth        731 non-null    int64  
 5   holiday     731 non-null    int64  
 6   weekday     731 non-null    int64  
 7   workingday  731 non-null    int64  
 8   weathersit  731 non-null    int64  
 9   temp        731 non-null    float64
 10  atemp       731 non-null    float64
 11  hum         731 non-null    float64
 12  windspeed   731 non-null    float64
 13  rentals     731 non-null    int64  
dtypes: float64(4), int64(9), object(1)
memory usage: 80.1+ KB


In [5]:
bike_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 731 entries, 0 to 730
Data columns (total 14 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   instant     731 non-null    int64  
 1   dteday      731 non-null    object 
 2   season      731 non-null    int64  
 3   yr          731 non-null    int64  
 4   mnth        731 non-null    int64  
 5   holiday     731 non-null    int64  
 6   weekday     731 non-null    int64  
 7   workingday  731 non-null    int64  
 8   weathersit  731 non-null    int64  
 9   temp        731 non-null    float64
 10  atemp       731 non-null    float64
 11  hum         731 non-null    float64
 12  windspeed   731 non-null    float64
 13  rentals     731 non-null    int64  
dtypes: float64(4), int64(9), object(1)
memory usage: 80.1+ KB


In [6]:
type(bike_data)

pandas.core.frame.DataFrame

In [7]:
features=['season','mnth', 'holiday','weekday','workingday','weathersit','temp', 'atemp', 'hum', 'windspeed']
X = bike_data[features].values


y = bike_data['rentals'].values


print('Features:',X[:10], '\nLabels:', y[:10], sep='\n')

Features:
[[1.        1.        0.        6.        0.        2.        0.344167
  0.363625  0.805833  0.160446 ]
 [1.        1.        0.        0.        0.        2.        0.363478
  0.353739  0.696087  0.248539 ]
 [1.        1.        0.        1.        1.        1.        0.196364
  0.189405  0.437273  0.248309 ]
 [1.        1.        0.        2.        1.        1.        0.2
  0.212122  0.590435  0.160296 ]
 [1.        1.        0.        3.        1.        1.        0.226957
  0.22927   0.436957  0.1869   ]
 [1.        1.        0.        4.        1.        1.        0.204348
  0.233209  0.518261  0.0895652]
 [1.        1.        0.        5.        1.        2.        0.196522
  0.208839  0.498696  0.168726 ]
 [1.        1.        0.        6.        0.        2.        0.165
  0.162254  0.535833  0.266804 ]
 [1.        1.        0.        0.        0.        1.        0.138333
  0.116175  0.434167  0.36195  ]
 [1.        1.        0.        1.        1.        1.        

In [8]:
bike_data[features].values

array([[ 1.      ,  1.      ,  0.      , ...,  0.363625,  0.805833,
         0.160446],
       [ 1.      ,  1.      ,  0.      , ...,  0.353739,  0.696087,
         0.248539],
       [ 1.      ,  1.      ,  0.      , ...,  0.189405,  0.437273,
         0.248309],
       ...,
       [ 1.      , 12.      ,  0.      , ...,  0.2424  ,  0.752917,
         0.124383],
       [ 1.      , 12.      ,  0.      , ...,  0.2317  ,  0.483333,
         0.350754],
       [ 1.      , 12.      ,  0.      , ...,  0.223487,  0.5775  ,
         0.154846]])

In [9]:
type(X)

numpy.ndarray

In [10]:
type(y)

numpy.ndarray

After separating the dataset, we now have numpy arrays named X containing the features, and y containing the labels.

We could train a model using all of the data; but it's common practice in supervised learning to split the data into two subsets; a (typically larger) set with which to train the model, and a smaller "hold-back" set with which to validate the trained model. This enables us to evaluate how well the model performs when used with the validation dataset by comparing the predicted labels to the known labels. It's important to split the data randomly (rather than say, taking the first 70% of the data for training and keeping the rest for validation). This helps ensure that the two subsets of data are statistically comparable (so we validate the model with data that has a similar statistical distribution to the data on which it was trained).

To randomly split the data, we'll use the train_test_split function in the scikit-learn library. This library is one of the most widely used machine learning packages for Python.

In [11]:
from sklearn.model_selection import train_test_split

In [12]:
# Split data 70%-30% into training set and test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20,shuffle=True)


# '''
# 1: training data feature
# 2: testing data feature
# 3: training data target
# 4: testing data target
# '''

In [13]:
y_test

array([ 269, 2153, 1027,  137,  326,  251,  778,  394,  997,  243, 1511,
        163,  642, 2544,  439, 2235,  536,  855,  921, 1045,  466,  979,
        639,  892, 1988,  342, 1014, 2512,  956,  534, 1242,  834,  254,
        190,   61,  810, 2795, 1074,  167,  723, 1038,  774,  775,  909,
        155, 2135,  796,  694,  952,  750,  762,  613, 1338, 1514, 2355,
       1965, 2622,   15,  710, 2352, 1325,  615,  742, 3283,  639, 1058,
       1401,  253,  143,  477,  760,  819,  991,  516,   64,  198,  204,
       2345,   25,  310, 1264,  981, 1685,  830,  203, 1532,  515, 1521,
        529, 3031,  174,  254,  787,   41, 1524,  429,  244,  502,  373,
        975,  174,  424,   43, 1031,   73,  729, 2015, 1965,  370, 1433,
        222,  456,  568,  799,  166,  233, 1899,  178,  433,  951,  968,
       1750,  417,  695, 2397,  699,   95,  751,  384,  371,  764, 1504,
       1914, 2001, 1208,  192,  471,  834,  738,  467,  601,  891,  408,
       1088,  969,  832,  260])

In [14]:
print ('Training Set: %d rows\nTest Set: %d rows' % (X_train.shape[0], X_test.shape[0]))

Training Set: 584 rows
Test Set: 147 rows


In [ ]:
# Train the model
from sklearn.linear_model import LinearRegression

In [16]:
# Fit a linear regression model on the training set

model = LinearRegression().fit(X_train, y_train)

print (model)

LinearRegression()


In [17]:
predictions = model.predict(X_test)

In [18]:
 #predicted
print('Predicted labels: ', np.round(predictions, 0)[:10])
print('Actual labels   : ' ,y_test[:10])

Predicted labels:  [ 235. 1867.  859.  136.   68.  923. 1423.  402.  909.  352.]
Actual labels   :  [ 269 2153 1027  137  326  251  778  394  997  243]


In [19]:
from sklearn.metrics import mean_squared_error, r2_score

mse = mean_squared_error(y_test, predictions)
print("MSE:", mse)

rmse = np.sqrt(mse)
print("RMSE:", rmse)

r2 = r2_score(y_test, predictions)
print("R2:", r2)

MSE: 149161.45968550336
RMSE: 386.2142665483803
R2: 0.6974203929575165


In [20]:
model

LinearRegression()

In [21]:
pwd

'c:\\Mine\\Machine Learning'

In [22]:
import joblib

In [ ]:
joblib.dump(model, "bike_model.pkl") #writing step

['bike_model.pkl']

In [24]:
# Load the model from the file
loaded_model = joblib.load("bike_model.pkl")

In [25]:
bike_data.head(1)

instant    dteday  season  yr  mnth  holiday  weekday  workingday  \
0        1  1/1/2011       1   0     1        0        6           0   

   weathersit      temp     atemp       hum  windspeed  rentals  
0           2  0.344167  0.363625  0.805833   0.160446      331

In [26]:
season=float(input("Enter the season"))
month=float(input("Enter the month"))
holiday=float(input("Enter the holiday"))
weekday=float(input("Enter the weekday"))
workingday=float(input("Enter the workingday"))
weathersit=float(input("Enter the weathersit"))
temp=float(input("Enter the temp"))
atemp=float(input("Enter the atemp"))
hum=float(input("Enter the hum"))
windspeed=float(input("Enter the windspeed"))

In [27]:
X_new = np.array([[season,month,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed]])
result = loaded_model.predict(X_new)
print('Prediction: {:.0f} rentals'.format(np.round(result[0])))

Prediction: -27014 rentals


In [28]:
X_new = np.array([[season,month,holiday,weekday,workingday,weathersit,temp,atemp,hum,windspeed]])
X_new

array([[ 1.,  2.,  0.,  1.,  0.,  1., 40., 46., 80., 60.]])

In [29]:
# Use the model to predict tomorrow's rentals
result = loaded_model.predict(X_new)
print('Prediction: {:.0f} rentals'.format(np.round(result[0])))

Prediction: -27014 rentals
